// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1U1QwPn_lOGyB3UUHPuRTPbKAAWchYA',
    appId: '1:646160000499:web:9974dc6cd81ca58e6dde86',
    messagingSenderId: '646160000499',
    projectId: 'foodorder-c6bbf',
    authDomain: 'foodorder-c6bbf.firebaseapp.com',
    storageBucket: 'foodorder-c6bbf.appspot.com',
    measurementId: 'G-4B0CRNM34B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCramMFa9WJwvPY1lna5U0jmJYpdf46gCo',
    appId: '1:646160000499:android:c0db822524a54d0c6dde86',
    messagingSenderId: '646160000499',
    projectId: 'foodorder-c6bbf',
    storageBucket: 'foodorder-c6bbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatxmjuNQTtgeUq2Z2ukkBEMydPsm58gw',
    appId: '1:646160000499:ios:0273c5c8446354d86dde86',
    messagingSenderId: '646160000499',
    projectId: 'foodorder-c6bbf',
    storageBucket: 'foodorder-c6bbf.appspot.com',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCatxmjuNQTtgeUq2Z2ukkBEMydPsm58gw',
    appId: '1:646160000499:ios:0273c5c8446354d86dde86',
    messagingSenderId: '646160000499',
    projectId: 'foodorder-c6bbf',
    storageBucket: 'foodorder-c6bbf.appspot.com',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ1U1QwPn_lOGyB3UUHPuRTPbKAAWchYA',
    appId: '1:646160000499:web:8b7da989f79a94e96dde86',
    messagingSenderId: '646160000499',
    projectId: 'foodorder-c6bbf',
    authDomain: 'foodorder-c6bbf.firebaseapp.com',
    storageBucket: 'foodorder-c6bbf.appspot.com',
    measurementId: 'G-P1CTXCGHMM',
  );
}
